---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Values.clusterrole.name }}
  labels:
    {{- include "bms-api.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.clusterrole.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceaccount.name }}
    namespace: {{ .Values.namespace }}
