---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Values.serviceaccount.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "bms-api.labels" . | nindent 4 }}
  {{- with .Values.serviceaccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
